# Generated by Django 4.1.1 on 2022-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="recipe_category",),
        migrations.AddField(
            model_name="product",
            name="recipe",
            field=models.CharField(default="recipe", max_length=500),
        ),
        migrations.AddField(
            model_name="product",
            name="recipe_type",
            field=models.CharField(default="food type", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
