# Generated by Django 4.1.1 on 2022-09-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeapp", "0002_remove_product_recipe_category_product_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="recipe",
            field=models.TextField(default="recipe"),
        ),
    ]
