# Generated by Django 4.1.1 on 2022-09-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeapp", "0003_alter_product_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="item_ingredients",
            field=models.TextField(default="ingredient"),
        ),
        migrations.AddField(
            model_name="product",
            name="recipe_aditonal",
            field=models.TextField(default="recipe"),
        ),
        migrations.AlterField(
            model_name="product",
            name="items",
            field=models.TextField(default="ingredient"),
        ),
    ]
