# Generated by Django 4.1.1 on 2022-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeapp", "0004_product_item_ingredients_product_recipe_aditonal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="food type", max_length=200),
        ),
    ]
